specialites = {
    "Généraliste",
    "Cardiologue",
    "Pneumologue",
    "Dermatologue",
    "Pédiatre",
    "Neurologue",
    "Gastro-entérologue",
    "Endocrinologue",
    "Rhumatologue",
    "Ophtalmologue",
    "ORL",
    "Gynécologue",
    "Urologue",
    "Néphrologue",
    "Oncologue",
    "Hématologue",
    "Chirurgien général",
    "Chirurgien orthopédiste",
    "Chirurgien cardiaque",
    "Chirurgien plastique",
    "Radiologue",
    "Anesthésiste",
    "Médecin du sport",
    "Médecin du travail",
    "Psychiatre",
    "Psychologue",
    "Médecin urgentiste",
    "Allergologue",
    "Infectiologue",
    "Médecin interne",
    "Gériatre",
    "Médecin rééducateur"
}
